export const ALL_INSTRUCTOR_REQUEST = "ALL_INSTRUCTOR_REQUEST";
export const ALL_INSTRUCTOR_SUCCESS = "ALL_INSTRUCTOR_SUCCESS";
export const ALL_INSTRUCTOR_FAIL = "ALL_INSTRUCTOR_FAIL";

export const INSTRUCTOR_DETAILS_REQUEST = "INSTRUCTOR_DETAILS_REQUEST";
export const INSTRUCTOR_DETAILS_SUCCESS = "INSTRUCTOR_DETAILS_SUCCESS";
export const INSTRUCTOR_DETAILS_FAIL = "INSTRUCTOR_DETAILS_FAIL";
// NEW --> CREATE
export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";

export const ADMIN_INSTRUCTOR_REQUEST = "ADMIN_INSTRUCTOR_REQUEST";
export const ADMIN_INSTRUCTOR_SUCCESS = "ADMIN_INSTRUCTOR_SUCCESS";
export const ADMIN_INSTRUCTOR_FAIL = "ADMIN_INSTRUCTOR_FAIL";
// NEW --> CREATE
export const CREATE_INSTRUCTOR_REQUEST = "CREATE_INSTRUCTOR_REQUEST";
export const CREATE_INSTRUCTOR_SUCCESS = "CREATE_INSTRUCTOR_SUCCESS";
export const CREATE_INSTRUCTOR_RESET = "CREATE_INSTRUCTOR_RESET";
export const CREATE_INSTRUCTOR_FAIL = "CREATE_INSTRUCTOR_FAIL";

export const UPDATE_INSTRUCTOR_REQUEST = "UPDATE_INSTRUCTOR_REQUEST";
export const UPDATE_INSTRUCTOR_SUCCESS = "UPDATE_INSTRUCTOR_SUCCESS";
export const UPDATE_INSTRUCTOR_RESET = "UPDATE_INSTRUCTOR_RESET";
export const UPDATE_INSTRUCTOR_FAIL = "UPDATE_INSTRUCTOR_FAIL";

export const DELETE_INSTRUCTOR_REQUEST = "DELETE_INSTRUCTOR_REQUEST";
export const DELETE_INSTRUCTOR_SUCCESS = "DELETE_INSTRUCTOR_SUCCESS";
export const DELETE_INSTRUCTOR_RESET = "DELETE_INSTRUCTOR_RESET";
export const DELETE_INSTRUCTOR_FAIL = "DELETE_INSTRUCTOR_FAIL";
// REVIEWS --> CHECKS
export const ALL_CHECKS_REQUEST = "ALL_CHECKS_REQUEST";
export const ALL_CHECKS_SUCCESS = "ALL_CHECKS_REQUEST";
export const ALL_CHECKS_FAIL = "ALL_CHECKS_FAIL";

export const DELETE_CHECKS_REQUEST = "DELETE_CHECKS_REQUEST";
export const DELETE_CHECKS_SUCCESS = "DELETE_CHECKS_SUCCESS";
export const DELETE_CHECKS_RESET = "DELETE_CHECKS_RESET";
export const DELETE_CHECKS_FAIL = "DELETE_CHECKS_FAIL";

export const SLIDER_INSTRUCTOR_REQUEST = "SLIDER_INSTRUCTOR_REQUEST";
export const SLIDER_INSTRUCTOR_SUCCESS = "SLIDER_INSTRUCTOR_SUCCESS";
export const SLIDER_INSTRUCTOR_FAIL = "SLIDER_INSTRUCTOR_FAIL";

export const REMOVE_INSTRUCTOR_DETAILS = "REMOVE_INSTRUCTOR_DETAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";